name: summarizerbot
services:
  summarizerbot:
    public: true
    image: emekaboris/summarizerbot:latest
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 2000m
      memory: 3Gi
